tart_time:Mon Feb 19 13:23:34 EST 2018
The location of mpi is /usr/lib64/openmpi/bin/mpirun
The python is /home/prathyusha/anaconda3/bin/python
The pythonpath is /home/prathyusha/repos/pypospack:
Traceback (most recent call last):
  File "mc_sampler_iterate.py", line 220, in <module>
    pyposmat_app.run_all()
  File "mc_sampler_iterate.py", line 43, in run_all
    self.run_simulations(i)
  File "mc_sampler_iterate.py", line 88, in run_simulations
    self.pyposmat_mc_sampler.configure_task_manager()
  File "/home/prathyusha/repos/pypospack/pypospack/pyposmat.py", line 478, in configure_task_manager
    structures = _structures)
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 80, in configure
    self.process_tasks()
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 176, in process_tasks
    task_structure=_task_structure)
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 200, in add_task
    self.structures['structures'][task_structure])
KeyError: 'Si'
Traceback (most recent call last):
  File "mc_sampler_iterate.py", line 220, in <module>
    pyposmat_app.run_all()
  File "mc_sampler_iterate.py", line 43, in run_all
    self.run_simulations(i)
  File "mc_sampler_iterate.py", line 88, in run_simulations
    self.pyposmat_mc_sampler.configure_task_manager()
  File "/home/prathyusha/repos/pypospack/pypospack/pyposmat.py", line 478, in configure_task_manager
    structures = _structures)
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 80, in configure
    self.process_tasks()
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 176, in process_tasks
    task_structure=_task_structure)
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 200, in add_task
    self.structures['structures'][task_structure])
KeyError: 'Si'
Traceback (most recent call last):
  File "mc_sampler_iterate.py", line 220, in <module>
    pyposmat_app.run_all()
  File "mc_sampler_iterate.py", line 43, in run_all
    self.run_simulations(i)
  File "mc_sampler_iterate.py", line 88, in run_simulations
    self.pyposmat_mc_sampler.configure_task_manager()
  File "/home/prathyusha/repos/pypospack/pypospack/pyposmat.py", line 478, in configure_task_manager
    structures = _structures)
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 80, in configure
    self.process_tasks()
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 176, in process_tasks
    task_structure=_task_structure)
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 200, in add_task
    self.structures['structures'][task_structure])
KeyError: 'Si'
Traceback (most recent call last):
  File "mc_sampler_iterate.py", line 220, in <module>
    pyposmat_app.run_all()
  File "mc_sampler_iterate.py", line 43, in run_all
    self.run_simulations(i)
  File "mc_sampler_iterate.py", line 88, in run_simulations
    self.pyposmat_mc_sampler.configure_task_manager()
  File "/home/prathyusha/repos/pypospack/pypospack/pyposmat.py", line 478, in configure_task_manager
    structures = _structures)
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 80, in configure
    self.process_tasks()
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 176, in process_tasks
    task_structure=_task_structure)
  File "/home/prathyusha/repos/pypospack/pypospack/task/task_manager.py", line 200, in add_task
    self.structures['structures'][task_structure])
KeyError: 'Si'
stop_time:Mon Feb 19 13:23:37 EST 2018

